### PR TITLE
Add MiMa previous artifact for Scalafix rule project

### PR DESCRIPTION
**Pull request by DavidGregory084**
This might need some time for Maven Central sync.

### CODE REVIEW

**Comment by DavidGregory084** [comment]
Hmm, I'm not sure that I've seen this one before

```
[error] java.lang.RuntimeException: Could not resolve previous ABI: io.github.davidgregory084:sbt-tpolecat-scalafix_2.12:0.4.1 (e:info.versionScheme=early-semver)
```

Seems like this happens when MiMa [can't find any matching jar file](https://github.com/lightbend/mima/blob/b20f56d9af7543ecbf7c78fe997ca0cf4e3b2a69/sbtplugin/src/main/scala/com/typesafe/tools/mima/plugin/SbtMima.scala#L107=).

**Comment by armanbilge** [comment]
Without getting some debug breakpoints into that MiMa source you linked I have no idea what's going on 😅

**Comment by armanbilge** [comment]
FWIW I compared the POM for these rules vs the typelevel-scalafix rules which seem to be working ok with MiMa. Nothing jumped out to me.

https://repo1.maven.org/maven2/io/github/davidgregory084/sbt-tpolecat-scalafix_2.12/0.4.1/sbt-tpolecat-scalafix_2.12-0.4.1.pom

https://repo1.maven.org/maven2/org/typelevel/typelevel-scalafix-cats_2.12/0.1.5/typelevel-scalafix-cats_2.12-0.1.5.pom

**Comment by DavidGregory084** [comment]
Hmm I can't replicate this locally, I wonder if I was just trying to run this too early

**Comment by DavidGregory084** [comment]
Hmmm nope, seems pretty persistent

**Comment by DavidGregory084** [comment]
Well that was an utterly miserable thing to debug...

Metals crashes on attach when you try to specify a -build module as a debug target. IntelliJ can't attach sources for sbt plugins automatically and won't step through for comprehensions. When I try to evaluate expressions in IntelliJ it complains that there's no Scala SDK attached to the sbt-tpolecat-build module (although there definitely is).

Regardless I think the problem is this:

image

The `artifact.name` that was resolved by Coursier does not have the Scala version suffix so it doesn't match the `module.name` that MiMa is searching for.

So I think the culprit here might be this syntax after all:

```scala
Set((project / projectID).value.withRevision("0.4.1")
```

**Comment by DavidGregory084** [comment]
As usual the secret sauce was something you have already done in [TypelevelMimaPlugin](https://github.com/typelevel/sbt-typelevel/blob/series/0.4/mima/src/main/scala/org/typelevel/sbt/TypelevelMimaPlugin.scala#L88=) @armanbilge - I don't know what `explicitArtifacts` are or why they have the wrong version suffix, but that fixes the problem. 😆

**Pull request merged**
